<Project>
  <PropertyGroup>
    <Version>0.7.0</Version>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!-- NuGet package improvements for packable projects -->
  <PropertyGroup Condition="'$(IsPackable)' == 'true'">
    <EmbedAllSources>true</EmbedAllSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.*" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.*" PrivateAssets="All" />
  </ItemGroup>
</Project>
